#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

const BASE_FILEPATH = __DIR__;

chdir(__DIR__.'/dist');

echo "Cleaning dist folder\n";
exec('rm -r *');

echo "Copying images\n";
exec('cp -r ../resources/images .');
exec('rm images/.gitignore');

echo "Compiling pages\n";
$twig = \App\Actions\GetPreparedTwig::run(__DIR__.'/templates');

$files = [
    '/' => 'index.html.twig',
    '/donate' => 'donate.html.twig',
];
$data = array_merge(include('../data.php'), ['env' => 'production']);
foreach($files as $path => $file) {
    $template = $twig->resolveTemplate($file);
    if (! is_dir(".$path")) {
        mkdir(".$path");
    }
    file_put_contents(".$path/index.html", $template->render(array_merge($data, [
        'current_uri' => $path,
    ])));
}

echo "Running Tailwind CSS";
chdir('..');
exec('npx tailwindcss -i ./resources/css/app.css -o ./dist/style.css --minify');